
language: elixir

elixir:
  - 1.6.0
  - 1.6.6
  - 1.7.0
  - 1.7.1
  - 1.7.2
  - 1.7.3
otp_release:
  - 20.2
  - 20.3
  - 21.0

matrix:
  exclude:
    - elixir: 1.6.0
      otp_release: 21.0

dist: trusty

addons:
  postgresql: "9.6"

services:
  - rabbitmq

env:
  - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - curl -o- -L https://yarnpkg.com/install.sh | sh -s -- --version 1.9.4

before_script:
  - psql -c 'create database ex_subtil_backend_test;' -U postgres
  - mkdir priv/repo/migrations
  - echo -n 0.0.0 > VERSION

scripts:
  - if [[ $(elixir --version) = *"1.7"* ]]; then mix format --check-formatted; fi
  - mix test
  - cd assets && ../yarn && ../yarn run lint && ../yarn run release
